name: jesi_dart_analysis
description: A package providing lint rules for Dart and Flutter which are used at JESI
version: 3.0.0
homepage: https://github.com/jesims/jesi_dart_analysis
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  flutter_lints: ^2.0.0
